spring:
  application:
    name: depart-consumer
  cloud:
    nacos:
      config:
        server-addr: localhost:8847
        username: nacos
        password: nacos
        file-extension: yml
        #共享配置文件
        shared-configs:
         - data-id: common.yml
           refresh: true
    sentinel:
      transport:
        dashboard: localhost:8888
      eager: true
      datasource:
        flows:
          nacos:
            server-addr: localhost:8847
            rule-type: flow
            data-id: ${spring.application.name}-flow-rules
            data-type: json
            username: nacos
            password: nacos
            group-id: SENTINEL_GROUP
        degrades:
          nacos:
            server-addr: localhost:8847
            rule-type: degrade
            username: nacos
            password: nacos
            data-type: json
            data-id: ${spring.application.name}-degrade-rules
            group-id: SENTINEL_GROUP
  config:
    import:
      - optional:nacos:common.yml
      - optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}